all: materialize.min.js materialize.min.css

materialize.min.css:
	wget https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/$@
materialize.min.js:
	wget https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/$@
